#!/bin/sh
dbus fire onnatstart
ifconfig eth0:1 192.168.1.200 netmask 255.255.255.0
iptables -t nat -I POSTROUTING -o eth0 -d 192.168.1.0/24 -j MASQUERADE
ip addr add 192.168.99.1/24 dev eth0
iptables -I INPUT -i eth0 -m state --state NEW -j ACCEPT
iptables -I FORWARD -i eth0 -o ppp0 -j ACCEPT
sleep 5
sh /koolshare/ss/nat-start.sh start_all
